# Importing necessary packages.
import os

# Necessary configuration specifications.
class AppConfig():
	SQLALCHEMY_DATABASE_URI = "sqlite:///../database/eyecatchers.db/"
	DEBUG = True
	SECURITY_PASSWORD_HASH = "bcrypt"
	try:
		SECRET_KEY = os.environ['SECRET_KEY']
		SECURITY_PASSWORD_SALT = os.environ['SECURITY_PASSWORD_SALT']
	except:
		SECRET_KEY = 'Confiding!Bucked0!Width'
		SECURITY_PASSWORD_SALT = 'PF&oRX9oTbQcRD4'
	SQLALCHEMY_TRACK_MODIFICATIONS = False
	WTF_CSRF_ENABLED = False
	SECURITY_TOKEN_AUTHENTICATION_HEADER = "Authentication-Token"
	SECURITY_EMAIL_SENDER = 'eyecatchershead@gmail.com'
	#SECURITY_REGISTER_USER_TEMPLATE = ''
	#SECURITY_POST_REGISTER_VIEW = ''
	#SECURITY_POST_CHANGE_VIEW = ''
	#SECURITY_CHANGE_PASSWORD_TEMPLATE = ''
	#SECURITY_POST_LOGIN_VIEW = ''
	#SECURITY_POST_LOGOUT_VIEW = ''
	#SECURITY_UNAUTHORIZED_VIEW = ''
	#SECURITY_LOGIN_USER_TEMPLATE = ''
	#SECURITY_RESET_PASSWORD_TEMPLATE = ''
	#SECURITY_FORGOT_PASSWORD_TEMPLATE = ''
	#SECURITY_POST_RESET_VIEW = ''